# Generated by Django 6.0 on 2026-09-05 06:23

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ocr_api_key',
            field=accounts.fields.EncryptedCharField(blank=True, default='', help_text='Your Anthropic or OpenAI API key. Stored encrypted at rest.', max_length=500),
        ),
    ]
